server:
  port: 8080

micronaut:
  router:
    expose-route-mapping: true
  management:
    endpoints:
      all:
        enabled: true
        sensitive: false
      routes:
        enabled: true
        sensitive: false
        expose: true
  application:
    name: vehicle-status-service
  http:
    services:
      insurance:
        urls: https://insurance.com
      maintenance:
        urls: https://topgarage.com
  logging:
    level:
      ROOT: DEBUG
      io.micronaut.http.client: TRACE
      io.micronaut.http.server: TRACE

  jackson:
    enabled: true
  serialization:
    enabled: false
